[project]
authors = [{name = "yamah-msky", email = "github2@mbmsky.dev"}]
dependencies = ["pandas==3.0.3", "matplotlib>=3.8.4,<3.9", "ipykernel>=7.3.0,<8", "ipython>=9.16.1,<10", "jupyterlab>=4.6.3,<5", "polars>=1.43.2,<2", "seaborn>=0.13.2,<0.14", "arrow>=1.4.0,<2", "ruff>=0.16.3,<0.17", "pydantic>=2.13.4,<3", "typer>=0.27.1,<0.28", "hichip-peaks>=0.1.2,<0.2", "numpy", "higlass-manage>=0.8.0,<0.9", "cloops2>=0.0.3,<0.0.4"]
name = "hichipbase2"
requires-python = ">= 3.11"
version = "0.1.0"
readme = "README.md"
license  = { text = "MIT" }

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.workspace]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
hichipbase2 = { path = ".", editable = true }

[tool.hatch.build.targets.wheel]
packages = ["src/hichipbase2"]

[tool.pixi.tasks]
higlass-start = "mkdir -p \"$PIXI_PROJECT_ROOT/work/results/higlass-data\" \"$PIXI_PROJECT_ROOT/work/results/higlass-tmp\" && higlass-manage start --hg-name default --port 8989 --version latest --data-dir \"$PIXI_PROJECT_ROOT/work/results/higlass-data\" --temp-dir \"$PIXI_PROJECT_ROOT/work/results/higlass-tmp\""
higlass-stop = "higlass-manage stop default"

[tool.pixi.dependencies]
python = "==3.11"
pip = ">=26.2.1,<27"
bwa-mem2 = ">=2.3,<3"
samtools = ">=1.24,<2"
pairtools = ">=1.1.3,<2"
bedtools = ">=2.31.1,<3"
circos = ">=0.69.9,<0.70"
cooler = ">=0.10.4,<0.11"
cooltools = ">=0.7.1,<0.8"
pycirclize = ">=1.10.1,<2"
biopython = ">=1.88,<2"
hatchling = ">=1.32.0,<2"
deeptools = ">=3.5.5,<4"
fastqc = ">=0.12.1,<0.13"
multiqc = ">=1.35,<2"
fastp = ">=1.3.6,<2"
numpy = ">=1.26.4,<2"
pandas = "==3.0.3"
matplotlib-base = ">=3.8.4,<3.9"
pygenometracks = ">=3.9,<4"
gffread = ">=0.12.9,<0.13"
jupyter_events = ">=0.12.1,<0.13"
coolbox = ">=0.4.0,<0.5"
ucsc-bedgraphtobigwig = ">=482,<483"
macs3 = ">=3.0.4,<4"
